import type { RuleDefinition } from "./types";

const base = (rule: Omit<RuleDefinition, "version" | "confidencePolicy" | "references">): Readonly<RuleDefinition> => Object.freeze({
  ...rule, version: "1.2.0", confidencePolicy: "HIGH only when required evidence is complete and retrieved.",
  requiredEvidence: Object.freeze([...rule.requiredEvidence]), knownLimitations: Object.freeze([...rule.knownLimitations]),
  references: Object.freeze(["SYNTHETIC DEMO RULE"]),
});

export const ruleDefinitions = Object.freeze({
  "SG-001": base({ ruleId: "SG-001", title: "Unrestricted SSH ingress", service: "EC2", applicableResourceType: "AWS::EC2::SecurityGroup", category: "NETWORK", description: "Detects TCP/22 ingress from an unrestricted IPv4 or IPv6 CIDR.", requiredEvidence: ["DescribeSecurityGroups"], evaluationContract: "Complete ingress evidence is required.", defaultSeverity: "HIGH", severityRationale: "Administrative SSH exposure can increase attack surface.", remediationGuidance: "Restrict SSH to approved management CIDRs or remove the rule.", verificationCondition: "A recheck shows no TCP/22 ingress from 0.0.0.0/0 or ::/0.", knownLimitations: ["Does not prove workload attachment or end-to-end Internet reachability."] }),
  "SG-002": base({ ruleId: "SG-002", title: "Unrestricted all protocols", service: "EC2", applicableResourceType: "AWS::EC2::SecurityGroup", category: "NETWORK", description: "Detects unrestricted all-protocol ingress.", requiredEvidence: ["DescribeSecurityGroups"], evaluationContract: "Complete ingress evidence is required.", defaultSeverity: "HIGH", severityRationale: "Unrestricted all-protocol ingress expands attack surface.", remediationGuidance: "Restrict protocol and CIDR ranges to the minimum required.", verificationCondition: "A recheck shows no all-protocol rule from 0.0.0.0/0.", knownLimitations: ["Does not prove workload attachment or end-to-end reachability."] }),
  "S3-001": base({ ruleId: "S3-001", title: "Public exposure indicators", service: "S3", applicableResourceType: "AWS::S3::Bucket", category: "DATA_EXPOSURE", description: "Evaluates complete policy-status evidence for public exposure.", requiredEvidence: ["GetPublicAccessBlock", "GetBucketPolicyStatus"], evaluationContract: "Policy status must be available to reach PASS or FAIL.", defaultSeverity: "HIGH", severityRationale: "Public buckets may expose data.", remediationGuidance: "Review bucket policy and public access controls.", verificationCondition: "A recheck returns IsPublic false with complete evidence.", knownLimitations: ["Public Access Block disabled alone is a configuration signal, not confirmed public access."] }),
  "S3-002": base({ ruleId: "S3-002", title: "Default encryption configuration", service: "S3", applicableResourceType: "AWS::S3::Bucket", category: "DATA_PROTECTION", description: "Checks default bucket encryption configuration.", requiredEvidence: ["GetEncryptionConfiguration"], evaluationContract: "Complete encryption configuration evidence is required.", defaultSeverity: "MEDIUM", severityRationale: "Default encryption supports data-protection expectations.", remediationGuidance: "Configure default bucket encryption.", verificationCondition: "A recheck observes default encryption enabled.", knownLimitations: ["This is a SHOULD_HAVE control."] }),
  "RDS-001": base({ ruleId: "RDS-001", title: "RDS public-access configuration enabled", service: "RDS", applicableResourceType: "AWS::RDS::DBInstance", category: "NETWORK", description: "Checks the PubliclyAccessible configuration flag.", requiredEvidence: ["DescribeDBInstances"], evaluationContract: "Complete DB instance evidence is required.", defaultSeverity: "HIGH", severityRationale: "Public-access configuration can increase exposure relevance.", remediationGuidance: "Disable public accessibility unless explicitly required and approved.", verificationCondition: "A recheck observes PubliclyAccessible false.", knownLimitations: ["Does not establish end-to-end Internet reachability."] }),
  "RDS-002": base({ ruleId: "RDS-002", title: "Storage encryption disabled", service: "RDS", applicableResourceType: "AWS::RDS::DBInstance", category: "DATA_PROTECTION", description: "Checks the StorageEncrypted configuration flag.", requiredEvidence: ["DescribeDBInstances"], evaluationContract: "Complete DB instance evidence is required.", defaultSeverity: "HIGH", severityRationale: "Unencrypted storage can increase data-at-rest risk.", remediationGuidance: "Enable storage encryption through an approved migration path.", verificationCondition: "A recheck observes StorageEncrypted true.", knownLimitations: ["Configuration only; no data classification is inferred."] }),
} as const);

export type SupportedRuleId = keyof typeof ruleDefinitions;
